version: "3.7"

services:
  db:
    image: postgres:14
    container_name: db_app
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
  app:
    build: .
    container_name: app
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - db
    command: ["src/fa_project/app.sh"]
