"""create association table

Revision ID: 819ec0a79905
Revises: 621dfebe6ddf
Create Date: 2024-03-29 11:50:38.970451

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '819ec0a79905'
down_revision: Union[str, None] = '621dfebe6ddf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('association',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('post', sa.Column('association_id', sa.Integer(), nullable=True))
    op.create_foreign_key('fk_post_association_id', 'post', 'association', ['association_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.add_column('tag', sa.Column('association_id', sa.Integer(), nullable=True))
    op.create_foreign_key('fk_tag_association_id', 'tag', 'association', ['association_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_tag_association_id', 'tag', type_='foreignkey')
    op.drop_column('tag', 'association_id')
    op.drop_constraint('fk_post_association_id', 'post', type_='foreignkey')
    op.drop_column('post', 'association_id')
    op.drop_table('association')
    # ### end Alembic commands ###
