"""add post in user

Revision ID: 8f5b91835cee
Revises: e3ef1ff64828
Create Date: 2023-12-15 16:07:51.914806

"""
from typing import Sequence, Union

import fastapi_users_db_sqlalchemy
from alembic import op
import sqlalchemy as sa

from src.fa_project.database.base import Base

# revision identifiers, used by Alembic.
revision: str = '8f5b91835cee'
down_revision: Union[str, None] = 'e3ef1ff64828'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('image', sa.String(), nullable=False),
    sa.Column('user_id', fastapi_users_db_sqlalchemy.generics.GUID(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='fk_post_user_id', onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('user', 'role_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    role = Base.metadata.tables['role']
    # ### end Alembic commands ###
    op.bulk_insert(role, [
        {'id': 1, 'name': 'admin', 'permissions': 1},
        {'id': 2, 'name': 'user', 'permissions': 0}
    ])
    # ### end Alembic commands ###



def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'role_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_table('post')
    # ### end Alembic commands ###
